INFO:root:Started
INFO:root:Started
INFO:root:Started
INFO:root:Started
ERROR:app:Exception on /_list_videos [GET]
Traceback (most recent call last):
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\twelvedogs\code\music_pump\app.py", line 261, in list_videos
    return jsonify(videos= Video.get_all())
  File "C:\Users\twelvedogs\code\music_pump\video.py", line 98, in get_all
    conn = sqlite3.connect(cfg.db_path)
sqlite3.OperationalError: unable to open database file
ERROR:app:Exception on /_get_queue [GET]
Traceback (most recent call last):
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\twelvedogs\code\music_pump\app.py", line 253, in get_queue
    return jsonify(queue=player.get_queue())
  File "C:\Users\twelvedogs\code\music_pump\player.py", line 216, in get_queue
    conn = sqlite3.connect(cfg.db_path)
sqlite3.OperationalError: unable to open database file
ERROR:pychromecast.controllers.media:Exception thrown when calling media status callback
Traceback (most recent call last):
  File "C:\Users\twelvedogs\.virtualenvs\music_pump-Mc7mz7Xp\lib\site-packages\pychromecast\controllers\media.py", line 482, in _fire_status_changed
    listener.new_media_status(self.status)
  File "C:\Users\twelvedogs\code\music_pump\player.py", line 84, in new_media_status
    self.advance_queue()
  File "C:\Users\twelvedogs\code\music_pump\player.py", line 124, in advance_queue
    conn = sqlite3.connect(cfg.db_path)
sqlite3.OperationalError: unable to open database file
INFO:root:Started
